# helm chart for a postgres database
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
      - port: 5432
  selector:
      app: postgres
      tier: backend
      release: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
    serviceName: postgres
    replicas: 1
    selector:
        matchLabels:
          app: postgres
          tier: backend
          release: postgres
    template:
        metadata:
          labels:
              app: postgres
              tier: backend
              release: postgres
        spec:
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ include "helm.fullname" . }}
          {{- end }}
          containers:
            - name: postgres
              image: postgres:9.6
              env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-password
                    key: postgres-password
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    key: user
                    name: postgres
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    key: database
                    name: postgres
              - name: POSTGRES_HOST
                valueFrom:
                  configMapKeyRef:
                    key: host
                    name: postgres

              ports:
              - containerPort: 5432
                name: postgres
              {{- if .Values.database.persistence.enabled }}
              volumeMounts:
              - name: postgres-persistent-storage
                mountPath: /var/lib/postgresql/data
                subPath: postgres
    volumeClaimTemplates:
    - metadata:
        name: postgres-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
            requests:
              storage: 1Gi
              {{- end }}
---
# generate a secret for the postgres password
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
type: Opaque
data:
  {{- if .Values.database.credentials.generatePassword }}
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "postgres-password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $postgresSecret := (get $secretData "postgres-password") | default (randAlphaNum 32 | b64enc) }}
  postgres-password: {{ $postgresSecret | quote }}
  {{- else}}
  postgres-password: {{ .Values.database.credentials.password | b64enc }}
  {{- end}}
---
# configmap for the postgres database
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
data:
  database: {{ .Values.database.dbName | quote }}
  host: "postgres"
  user: {{ .Values.database.credentials.user | quote }}
  port: "5432"