---
version: '3'

services:
  app:
    container_name: "app"
    image: "${APP_IMAGE_TAG}"
    environment:
      DB_HOSTNAME: "db"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "5432"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:80/health"]
      interval: 5s
    ports:
      - '8080:80'
  migrations:
    container_name: "migrations"
    image: "${APP_IMAGE_TAG}"
    command: "migrate"
    environment:
      DB_HOSTNAME: "db"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "5432"
    depends_on:
      - db
    restart: on-failure