---
version: '3'

services:
  app:
    container_name: "app"
    image: "${APP_IMAGE_TAG}"
    environment:
      TARGET_DB_HOST: "db"
      TARGET_DB_USER: "${TARGET_DB_USER}"
      TARGET_DB_PW: "${TARGET_DB_PW}"
      TARGET_DB: "${TARGET_DB}"
      TARGET_DB_PORT: "5432"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:80/health"]
      interval: 5s
    ports:
      - '8080:80'