// Jenkinsfile executing in two containers on the same node
pipeline {
    // Assuming python 3.10 and docker / docker compose are available on the main node.
    agent {
        kubernetes {
            defaultContainer 'python'
            yaml """
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    jenkins: build-node
                spec:
                    serviceAccountName: service-account
                    containers:
                    - name: python
                      image: ghcr.io/rocs-org/python-test-environment:latest
                      command:
                      - cat
                      tty: true
                      env:
                      - name: http_proxy
                        value: http://10.15.156.29:8020
                      - name: https_proxy
                        value: http://10.15.156.29:8020
                      - name: NO_PROXY
                        value: localhost
                      - name: DB_PASSWORD
                        value: password
                      - name: DB_USER
                        value: user
                      - name: DB_NAME
                        value: test_db
                      - name: DB_HOSTNAME
                        value: localhost
                      - name: DB_PORT
                        value: 5432
                      ports:
                      - containerPort: 8080
                      resources:
                        requests:
                          ephemeral-storage: 1Gi
                    - name: postgres
                      image: postgres:latest
                      tty: true
                      env:
                      - name: POSTGRES_PASSWORD
                        value: password
                      - name: POSTGRES_USER
                        value: user
                      - name: POSTGRES_DB
                        value: test_db
                      ports:
                      - containerPort: 5432
                      readinessProbe:
                        exec:
                          command:
                          - pg_isready
                          - -U
                          - user
                      resources:
                        requests:
                          ephemeral-storage: 100Mi
                    - name: helm
                      image: alpine/helm:latest
                      tty: true
                      command:
                        - cat
                      resources:
                        requests:
                          ephemeral-storage: 100Mi
                    - name: kaniko
                      image: gcr.io/kaniko-project/executor:debug
                      command:
                        - cat
                      tty: true
                      env:
                      - name: HTTP_PROXY
                        value: http://10.15.156.29:8020
                      - name: HTTPS_PROXY
                        value: http://10.15.156.29:8020
                      - name: NO_PROXY
                        value: harbor-dev.tkpoc.it32.labor
                      - name: HARBOR_HOST
                        value: harbor-dev.tkpoc.it32.labor
                      resources:
                        requests:
                          ephemeral-storage: 1Gi
                    tolerations:
                    - key: "node.kubernetes.io/not-ready"
                      operator: "Exists"
                      effect: "NoExecute"
                      tolerationSeconds: 900
                    restartPolicy: Never
                """
            }
    }
    stages {
        stage('Setup'){
            steps {
                sh 'poetry --version'
                // Checkout the code
                checkout scm
                // Install dependencies
                sh 'make install'
                // 'run database migrations'
                sh 'make migrate'
            }
        }
        stage('Test and lint') {
            steps {
                // Run linting
                sh 'make lint'
                // Run tests
                sh 'make test'
            }
        }
        stage('Helm tests') {
            steps {
                container('helm') {
                    sh 'helm version'
                    sh 'helm upgrade --install python-rest-template charts/template -n jenkins-staging-scratch'
                    sh 'helm test python-rest-template'
                    sh 'helm uninstall python-rest-template'
                }
            }
        }
        stage('Build and publish') {
            when {
                branch 'main'
            }
            steps {
                container('kaniko') {
                    withCredentials([usernamePassword(credentialsId: 'harbor', usernameVariable: 'username', passwordVariable: 'password')]) {
                        sh '''
                            # Setup login credentials for harbor. Note, you have to double escape the quotes because of
                            # https://stackoverflow.com/a/56596103

                            export TOKEN=$(echo -n $username:$password | base64 -w 0)
                            echo "{\\"auths\\":{\\"$HARBOR_HOST\\":{\\"username\\":\\"$username\\",\\"password\\":\\"$password\\",\\"auth\\":\\"$TOKEN\\"}}}" > /kaniko/.docker/config.json

                            # Build and publish the image. Note you have to pass the proxy as build args.

                            /kaniko/executor \
                            --dockerfile=docker/Dockerfile \
                            --context=dir://. \
                            --destination=$HARBOR_HOST/devops/python-rest-template:latest \
                            --skip-tls-verify-registry=$HARBOR_HOST \
                            --build-arg "http_proxy=$HTTP_PROXY" \
                            --build-arg "https_proxy=$HTTPS_PROXY" \
                            --build-arg "HTTP_PROXY=$HTTP_PROXY" \
                            --build-arg "HTTPS_PROXY=$HTTPS_PROXY"
                        '''
                    }
                }
            }
        }
    }
}
