pipeline {
    // Assuming python 3.10 and docker / docker compose are available on the main node.
    agent any
    stages {
        stage('Checkout Source') {
            steps {
                sh 'rm -rf python-rest-api'
                sh 'git clone https://github.com/jakobkolb/python-rest-api.git'
            }
        }
        stage('Setup Tooling'){
            steps {
                // Setup poetry
                sh 'curl -sSL https://install.python-poetry.org | python3 -'
                // Check that docker is available
                sh 'docker run hello-world'
            }
        }
        stage('Test and lint') {
            environment {
                // put poetry executable in PATH
                PATH = "${env.JENKINS_HOME}/.local/bin:${env.PATH}"
            }
            steps {
                dir('python-rest-api') {
                    sh 'echo $PATH'
                    sh 'make install'
                    sh 'make setup-db'
                    sh 'make lint'
                    sh 'make test'
                }
            }
        }
    }
    post {
        always {
            dir('python-rest-api') {
                sh 'make teardown'
            }
        }
    }
}