name: Publish App image

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push App Docker image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t python-rest-example:${{ github.ref_name }} . -f docker/Dockerfile

      - name: Publish docker image to github packages
        if: github.event_name == 'schedule' || github.event_name == 'push'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag python-rest-example:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/python-rest-example:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/python-rest-example:${{ github.ref_name }}